<?php

$jsonStreet_code = '{
  "streets":[
    {"code": "ACC", "desc": "Access"},
	{"code": "AL", "desc": "Alley"},
	{"code": "AMB", "desc": "Amble"},
	{"code": "ANC", "desc": "Anchorage"},
	{"code": "APP", "desc": "Approach"},
	{"code": "ARC", "desc": "Arcade"},
	{"code": "ATY", "desc": "Artery"},
	{"code": "AVE", "desc": "Avenue"},
	{"code": "AWY", "desc": "Alleyway"},
	{"code": "BAS", "desc": "Basin"},
	{"code": "BCH", "desc": "Beach"},
	{"code": "BLK", "desc": "Block"},
	{"code": "BLV", "desc": "Boulevard"},
	{"code": "BND", "desc": "Bend"},
	{"code": "BNK", "desc": "Bank"},
	{"code": "BPS", "desc": "Bypass"},
	{"code": "BR", "desc": "Brace"},
	{"code": "BRA", "desc": "Brae"},
	{"code": "BRG", "desc": "Bridge"},
	{"code": "BRK", "desc": "Break"},
	{"code": "BRW", "desc": "Brow"},
	{"code": "BWL", "desc": "Bowl"},
	{"code": "BWY", "desc": "Broadway"},
	{"code": "BYW", "desc": "Byway"},
	{"code": "CCT", "desc": "Circuit"},
	{"code": "CDS", "desc": "Cul-de-sac"},
	{"code": "CH", "desc": "Chase"},
	{"code": "CIR", "desc": "Circle"},
	{"code": "CL", "desc": "Close"},
	{"code": "CLD", "desc": "Colonnade"},
	{"code": "CLT", "desc": "Circlet"},
	{"code": "CMN", "desc": "Common"},
	{"code": "CNC", "desc": "Concourse"},
	{"code": "CNR", "desc": "Corner"},
	{"code": "CPS", "desc": "Copse"},
	{"code": "CRC", "desc": "Circus"},
	{"code": "CRD", "desc": "Crossroad"},
	{"code": "CRS", "desc": "Crescent"},
	{"code": "CRT", "desc": "Court"},
	{"code": "CRW", "desc": "Crossway"},
	{"code": "CSG", "desc": "Crossing"},
	{"code": "CSO", "desc": "Corso"},
	{"code": "CSW", "desc": "Cruiseway"},
	{"code": "CTR", "desc": "Centre"},
	{"code": "CTW", "desc": "Centreway"},
	{"code": "CUT", "desc": "Cutting"},
	{"code": "CVE", "desc": "Cove"},
	{"code": "CWY", "desc": "Causeway"},
	{"code": "CYD", "desc": "Courtyard"},
	{"code": "DAL", "desc": "Dale"},
	{"code": "DEL", "desc": "Dell"},
	{"code": "DIP", "desc": "Dip"},
	{"code": "DR", "desc": "Drive"},
	{"code": "DRY", "desc": "Driveway"},
	{"code": "DTR", "desc": "Distributor"},
	{"code": "DVN", "desc": "Deviation"},
	{"code": "EGE", "desc": "Edge"},
	{"code": "ELB", "desc": "Elbow"},
	{"code": "END", "desc": "End"},
	{"code": "ENT", "desc": "Entrance"},
	{"code": "ESP", "desc": "Esplanade"},
	{"code": "EST", "desc": "Estate"},
	{"code": "EXP", "desc": "Expressway"},
	{"code": "EXT", "desc": "Extension"},
	{"code": "FAY", "desc": "Fairway"},
	{"code": "FLT", "desc": "Flat"},
	{"code": "FLW", "desc": "Follow"},
	{"code": "FMN", "desc": "Formation"},
	{"code": "FR", "desc": "Frontage"},
	{"code": "FRT", "desc": "Front"},
	{"code": "FSR", "desc": "Foreshore"},
	{"code": "FTK", "desc": "Fire Track"},
	{"code": "FTL", "desc": "Firetrail"},
	{"code": "FTW", "desc": "Footway"},
	{"code": "FWY", "desc": "Freeway"},
	{"code": "GAP", "desc": "Gap"},
	{"code": "GDN", "desc": "Garden"},
	{"code": "GDS", "desc": "Gardens"},
	{"code": "GL", "desc": "Glade"},
	{"code": "GLN", "desc": "Glen"},
	{"code": "GLY", "desc": "Gully"},
	{"code": "GRA", "desc": "Grange"},
	{"code": "GRD", "desc": "Ground"},
	{"code": "GRN", "desc": "Green"},
	{"code": "GTE", "desc": "Gate"},
	{"code": "GTS", "desc": "Gates"},
	{"code": "GVE", "desc": "Grove "},
	{"code": "HIL", "desc": "Hill"},
	{"code": "HRD", "desc": "Highroad"},
	{"code": "HTS", "desc": "Heights"},
	{"code": "HWY", "desc": "Highway"},
	{"code": "ITC", "desc": "Interchange"},
	{"code": "ITS", "desc": "Intersection"},
	{"code": "JN", "desc": "Junction"},
	{"code": "KEY", "desc": "Key"},
	{"code": "LDG", "desc": "Landing"},
	{"code": "LEE", "desc": "Lees"},
	{"code": "LIN", "desc": "Line"},
	{"code": "LK", "desc": "Link"},
	{"code": "LKO", "desc": "Lookout"},
	{"code": "LOW", "desc": "Lower"},
	{"code": "LP", "desc": "Loop"},
	{"code": "LT", "desc": "Little"},
	{"code": "LWY", "desc": "Laneway"},
	{"code": "MAL", "desc": "Mall"},
	{"code": "MDR", "desc": "Meander"},
	{"code": "MEW", "desc": "Mew"},
	{"code": "ML", "desc": "Mile"},
	{"code": "MT", "desc": "Mount"},
	{"code": "MWS", "desc": "Mews"},
	{"code": "MWY", "desc": "Motorway"},
	{"code": "NK", "desc": "Nook"},
	{"code": "OUT", "desc": "Outlook"},
	{"code": "PDE", "desc": "Parade"},
	{"code": "PKL", "desc": "Parklands"},
	{"code": "PKT", "desc": "Pocket"},
	{"code": "PKW", "desc": "Parkway"},
	{"code": "PL", "desc": "Place"},
	{"code": "PLZ", "desc": "Plaza"},
	{"code": "PNT", "desc": "Point"},
	{"code": "PR", "desc": "Pier"},
	{"code": "PRK", "desc": "Park"},
	{"code": "PRM", "desc": "Promenade"},
	{"code": "PRT", "desc": "Part"},
	{"code": "PSS", "desc": "Pass"},
	{"code": "PT", "desc": "Port"},
	{"code": "PTH", "desc": "Path"},
	{"code": "PTU", "desc": "Plateau"},
	{"code": "PWY", "desc": "Parkway"},
	{"code": "PZA", "desc": "Piazza"},
	{"code": "QD", "desc": "Quadrant"},
	{"code": "QDG", "desc": "Quadrangle"},
	{"code": "QY", "desc": "Quay"},
	{"code": "QYS", "desc": "Quays"},
	{"code": "RA", "desc": "Ramble"},
	{"code": "RBL", "desc": "Rosebowl"},
	{"code": "RCH", "desc": "Reach"},
	{"code": "RD", "desc": "Road"},
	{"code": "RDE", "desc": "Ronde"},
	{"code": "RDG", "desc": "Ridge"},
	{"code": "RDS", "desc": "Roads"},
	{"code": "RDW", "desc": "Ridgeway"},
	{"code": "RDY", "desc": "Roadway"},
	{"code": "RES", "desc": "Reserve"},
	{"code": "RGE", "desc": "Range"},
	{"code": "RI", "desc": "Rise"},
	{"code": "RID", "desc": "Ride"},
	{"code": "RMP", "desc": "Ramp"},
	{"code": "RND", "desc": "Round"},
	{"code": "RNG", "desc": "Ring"},
	{"code": "ROW", "desc": "Row"},
	{"code": "RSD", "desc": "Roadside"},
	{"code": "RST", "desc": "Rest"},
	{"code": "RT", "desc": "Retreat"},
	{"code": "RTE", "desc": "Route"},
	{"code": "RTW", "desc": "Right of Way"},
	{"code": "RTY", "desc": "Rotary"},
	{"code": "RUE", "desc": "Rue"},
	{"code": "RUN", "desc": "Run"},
	{"code": "RVA", "desc": "Riviera"},
	{"code": "RVR", "desc": "River"},
	{"code": "RVW", "desc": "Riverway"},
	{"code": "SDG", "desc": "Siding"},
	{"code": "SHW", "desc": "Statehighway"},
	{"code": "SLP", "desc": "Slope"},
	{"code": "SND", "desc": "Sound"},
	{"code": "SPR", "desc": "Spur"},
	{"code": "SQ", "desc": "Square"},
	{"code": "ST", "desc": "Street"},
	{"code": "STA", "desc": "Stairs"},
	{"code": "STP", "desc": "Steps"},
	{"code": "SWY", "desc": "Service  Way"},
	{"code": "TCE", "desc": "Terrace"},
	{"code": "THF", "desc": "Thoroughfare"},
	{"code": "TKW", "desc": "Trunkway"},
	{"code": "TOP", "desc": "Top"},
	{"code": "TOR", "desc": "Tor"},
	{"code": "TR", "desc": "Track"},
	{"code": "TRI", "desc": "Triangle"},
	{"code": "TRL", "desc": "Trail"},
	{"code": "TRN", "desc": "Tarnice Way"},
	{"code": "TRR", "desc": "Trailer"},
	{"code": "TUR", "desc": "Turn"},
	{"code": "TWR", "desc": "Towers"},
	{"code": "TWY", "desc": "Tollway"},
	{"code": "UNP", "desc": "Underpass"},
	{"code": "UPR", "desc": "Upper"},
	{"code": "VAL", "desc": "Vale"},
	{"code": "VDT", "desc": "Viaduct"},
	{"code": "VLA", "desc": "Villa"},
	{"code": "VST", "desc": "Vista"},
	{"code": "VW", "desc": "View"},
	{"code": "WAY", "desc": "Way"},
	{"code": "WD", "desc": "Wade"},
	{"code": "WF", "desc": "Wharf"},
	{"code": "WK", "desc": "Walk"},
	{"code": "WKY", "desc": "Walkway"},
	{"code": "WND", "desc": "Wynd"},
	{"code": "YRD", "desc": "Yard"}
  ]
}';

$jsonLoan_type = '{
  "loantype":[
  	{"code": "auto", "desc": "car"},
	{"code": "auto", "desc": "motorbike"},
	{"code": "other", "desc": "boat"},
	{"code": "other", "desc": "jetski"},
	{"code": "other", "desc": "caravanrv"},
	{"code": "other", "desc": "caravan"},
	{"code": "other", "desc": "truck"},
	{"code": "other", "desc": "machineryequip"},
	{"code": "other", "desc": "equipment"},
	{"code": "other", "desc": "vehicle"},
	{"code": "other", "desc": "home"},
	{"code": "other", "desc": "excavator"},
	{"code": "other", "desc": "bulldozer"},
	{"code": "other", "desc": "skidsteer"},
	{"code": "other", "desc": "crane"},
	{"code": "other", "desc": "roller"},
	{"code": "other", "desc": "conveyer"},
	{"code": "other", "desc": "crusher"},
	{"code": "other", "desc": "personal"},
	{"code": "other", "desc": "cashflow"},
	{"code": "other", "desc": "businessloan"},
	{"code": "other", "desc": "other"},
        {"code": "other", "desc": "personal_loan"},
        {"code": "other", "desc": "truck_and_equipments"}
  ]
}';

$jsonMarital_status = '{
  "maritalstatus":[
  	{"code": "D", "desc": "divorced"},
  	{"code": "DF", "desc": "de_facto"},
  	{"code": "M", "desc": "married"},
  	{"code": "S", "desc": "single"},
  	{"code": "SPRTD", "desc": "separated"},
  	{"code": "W", "desc": "widow"}
  ]
}';

$jsonEmployment_type = '{
  "employementtype":[
  	{"code": "CASUL", "desc": "casual"},
  	{"code": "FTIME", "desc": "full_time"},
  	{"code": "OTR", "desc": "other"},
  	{"code": "PTIME", "desc": "part_time"},
  	{"code": "RETD", "desc": "retired"},
  	{"code": "SEMP", "desc": "self_employment"},
  	{"code": "UNEMP", "desc": "un_employed"}
  ]
}';

$jsonResidential_status = '{
  "residentialstatus":[
  	{"code": "O", "desc": "owned"},
  	{"code": "M", "desc": "mortgaged"},
  	{"code": "F", "desc": "livefamily"},
  	{"code": "R", "desc": "rented"},
  	{"code": "B", "desc": "boarder"},
  	{"code": "L", "desc": "lease"}
  ]
}';


$jsonSource_status = '{
  "sourcestatus":[
  	{"code": "RAD", "desc": "radio"},
  	{"code": "GGL", "desc": "google"},
  	{"code": "TV", "desc": "tv"},
  	{"code": "FB", "desc": "facebook"},
  	{"code": "NWPR", "desc": "newspaper"},
  	{"code": "MAG", "desc": "magazine"},
        {"code": "WOM", "desc": "word_of_mouth"}
  ]
}';


$coplCodes = array(
    "street_codes" => $jsonStreet_code,
    "loan_types" => $jsonLoan_type,
    "marital_statuses" => $jsonMarital_status,
    "employnents_types" => $jsonEmployment_type,
    "residential_statuses" => $jsonResidential_status,
    "source_statuses" => $jsonSource_status
);


$geniusConfig = array(
    "API_ENDPOINT" => "http://122.201.115.107/broker/webservice/application/new",
);
